### ISSUE TITLE
Why is it round

### ISSUE THREAD

**Issue by znnspace** [opensourceBIM/BIMsurfer#104]
In apps/dev.html, view the rounded model below . How to load the original model instead of the rounded bottom
![image](https://user-images.githubusercontent.com/25051018/156951412-8c32717e-5e3f-4b97-8fcc-d7cf03e73084.png)
![image](https://user-images.githubusercontent.com/25051018/156951424-a1eb22fb-f835-472d-a94f-7a0a23f30d4f.png)

**Comment by aothms** [comment]
It's this bit of code. https://github.com/opensourceBIM/BIMsurfer/blob/master/viewer%2Fshaders%2Ffragment.glsl.js#L41-L45 If you find the time a Pull Request making this configurable would be greatly appreciated.
