### ISSUE TITLE
How do I not load the model in the center of a div？

### ISSUE THREAD

**Issue by znnspace** [opensourceBIM/BIMsurfer#106]
How do I not load the model in the center of a div？

**Comment by aothms** [comment]
The camera is targeted at the 3d bounding box center. You can make changes to that https://github.com/opensourceBIM/BIMsurfer/blob/master/viewer/camera.js#L773 Or do a programmatic camera.pan() after the model finished loading https://github.com/opensourceBIM/BIMsurfer/blob/master/viewer/camera.js#L583
