### ISSUE TITLE
Some issues on bimsufferv3 and bimvie.ws

### ISSUE THREAD

**Issue by victor-freedom** [opensourceBIM/BIMsurfer#113]
![image](https://user-images.githubusercontent.com/131346088/237020315-21c39e37-def7-4415-91f7-db473605da43.png)

I use [BIMsurfer v3](https://github.com/opensourceBIM/bimsurfer) standalone to show the data,but it is not show completely. bimserver is v1.5.184
but in the bimvie.ws,it is not has the problem.![image](https://user-images.githubusercontent.com/131346088/237021052-afd6550c-583d-4b42-aa2f-e087fdc66e6e.png)

I have download the bimvie.ws project . I find it is not use the BIMsurferv3 to show the model data,it seems like to use scenejs to show the model data.The bimvie.ws project is very complicated,there is so many files ,I only know the entrance is 3dView.html,but,I can't run it.

So,Whether the BIMsurferv3 can show the data completely?
Whether the  https://github.com/opensourceBIM/bimvie.ws can run standalone?If it can,tell me how can i do and run it standalone

**Comment by aothms** [comment]
bimvie.ws is indeed hard to make sense of, I wouldn't start from that. It uses bimsurfer v1, which depends on SceneJS. All are very dated.

The thing with bimsurfer v3 and the bimserver API is that not all settings are stable. I think you have to enable the `prepareBuffers` setting in the latest version of bimserver, (you might need to experiment with some of the other settings, but start with `prepareBuffers`)

Maybe @hlg knows more.

**Comment by victor-freedom** [comment]
> bimvie.ws is indeed hard to make sense of, I wouldn't start from that. It uses bimsurfer v1, which depends on SceneJS. All are very dated.
> 
> The thing with bimsurfer v3 and the bimserver API is that not all settings are stable. I think you have to enable the `prepareBuffers` setting in the latest version of bimserver, (you might need to experiment with some of the other settings, but start with `prepareBuffers`)
> 
> Maybe @hlg knows more.

Thank you. Yesterday,I used BIMsurfer-before2019-master to show the 3dmodel successful in  bimserver v 1.5.184,because i I referenced the GeometryLoader.js code and modified the BimServerGeometryLoader.js.
I find the different between the BimServerGeometryLoader.js and GeometryLoader.js is binarygeometry data  reading,so i changed it and then success.
Now,I want you give me a advice
Which version do i use for?
Bimserver v1.5.88 and BIMsurfer-before2019-master
Bimserver v1.5.182 and BIMsurfer-before2019-master
Bimserver v1.5.182 and [BIMsurfer2](https://github.com/AECgeeks/BIMsurfer2)

**Comment by hlg** [comment]
I would recommend to stick with the latest BIMserver version.
