### ISSUE TITLE
I have two params quesiton

### ISSUE THREAD

**Issue by victor-freedom** [opensourceBIM/BIMsurfer#114]
https://github.com/opensourceBIM/BIMsurfer-before2019
I use this project to show the IFC file successful.But I have a request that I want to add a custom block to the main model。
![image](https://github.com/opensourceBIM/BIMsurfer/assets/131346088/47a6ca04-ff22-44cb-9c28-d8dc6a7d0925)
Look at picture,I want to add a blue block on the wall。
So，I find the method like bimSurfer.loadRandom();
Then I can show the block independent like this 
![image](https://github.com/opensourceBIM/BIMsurfer/assets/131346088/0087f54a-0d46-4027-9ae0-63ad1cc16231)
But I don't know how to set the block's size and position.I find some method params to control the display,but I don't know what they are mean.
First ,the camera
![image](https://github.com/opensourceBIM/BIMsurfer/assets/131346088/e004e253-4169-440e-8119-867ba652e29a)
what's the target,up,eye,far,near and fovy mean?
Second,I find the translationMat4c can decide the postion but I don't know how to set the block size or shape.If I want to add a cylinder or a triangle,How can I do that?
![image](https://github.com/opensourceBIM/BIMsurfer/assets/131346088/30a40ef2-7b5f-49f5-8b4f-b32263df4825)
If there any api document? If I know how to use this,I think I can add a block to the model where I want.

**Comment by aothms** [comment]
We cannot provide support for https://github.com/opensourceBIM/BIMsurfer-before2019 anymore. It's in a separate repository with a reason.

These parameters are standard view and projection matrix parameters e.g http://www.codinglabs.net/article_world_view_projection_matrix.aspx

If you use bimsurfer2 with threejs https://github.com/AECgeeks/BIMsurfer2/ it might be easier to add custom geometry. You just have a threejs scene, which is extensively documented.

**Comment by victor-freedom** [comment]
> We cannot provide support for https://github.com/opensourceBIM/BIMsurfer-before2019 anymore. It's in a separate repository with a reason.
> 
> These parameters are standard view and projection matrix parameters e.g http://www.codinglabs.net/article_world_view_projection_matrix.aspx
> 
> If you use bimsurfer2 with threejs https://github.com/AECgeeks/BIMsurfer2/ it might be easier to add custom geometry. You just have a threejs scene, which is extensively documented.

Thank you .But the bimsurfer2 with threejs https://github.com/AECgeeks/BIMsurfer2 isn't show how the display the IFC file from bimserver。It only shows the gltf.
the ThreeViewer only used by _loadFrom_glTF. _loadFromServer and loadRandom are still  use XeoViewer.
![image](https://github.com/opensourceBIM/BIMsurfer/assets/131346088/ad9c98a9-189a-4f77-a2d1-3bbab2bdea9d)

**Comment by victor-freedom** [comment]
> We cannot provide support for https://github.com/opensourceBIM/BIMsurfer-before2019 anymore. It's in a separate repository with a reason.
> 
> These parameters are standard view and projection matrix parameters e.g http://www.codinglabs.net/article_world_view_projection_matrix.aspx
> 
> If you use bimsurfer2 with threejs https://github.com/AECgeeks/BIMsurfer2/ it might be easier to add custom geometry. You just have a threejs scene, which is extensively documented.

Is there has any examples to show the data which is loaded from bimserver by the threejs ?
