### ISSUE TITLE
How to make setColor() for type similar to setVisibility()

### ISSUE THREAD

**Issue by sangdth** [opensourceBIM/BIMsurfer#22]
There are many time we (for example, init the project or reset the view), where we really want to setColor on massive number of objects, e.g. walls, spaces. I wonder if is it possible to make setColor with type like this:
```
bimSurfer.setColor({
    types: ['IfcWall'],
   color: [ ... color],
})
```

Thank you.

**Comment by aothms** [comment]
I think the repository you're looking for got moved suddenly: https://github.com/opensourceBIM/BIMsurfer-before2019

The code to iterate over types is indeed specifically implemented in the setVisibility function: https://github.com/opensourceBIM/BIMsurfer-before2019/blob/master/bimsurfer/src/xeoViewer/xeoViewer.js#L612

**Comment by sangdth** [comment]
Thank you, I will check it out.
