### ISSUE TITLE
Failed to execute 'clearBufferuiv' on 'WebGL2RenderingContext'

### ISSUE THREAD

**Issue by tecnodcp** [opensourceBIM/BIMsurfer#24]
Hi!

I have this error in the console

![image](https://user-images.githubusercontent.com/34940685/55065680-93f53c00-507c-11e9-8f3f-e7add22a1187.png)

The model is loaded and displayed. I can rotate the camera and zoom but i can't select elements. Any idea?

im' using BIMserver-JavaScript-Api commit af06dc6b8055481294b47f2a3757ccf51488886f
and BIMsurfer commit commit 3aebb6cf15108898dbaa5704093d1e5a5835512a

**Comment by tecnodcp** [comment]
The issue remains even with the last commint of BIMsurfer fabd8d4d8d3a5dfe52ed292d52a63ee7767986a9

**Comment by rubendel** [comment]
Which browser/version?

**Comment by tecnodcp** [comment]
Ubuntu google chrome Google Chrome 65.0.3325.162

**Comment by rubendel** [comment]
That's not safe at all, I would advice to upgrade to 73. Do you have a dedicated GPU or a virtual one? What is the output of: https://webglreport.com/?v=2 ?

**Comment by tecnodcp** [comment]
-I' will check with the upgraded version

-This is the output of  https://webglreport.com/?v=2 (With 65.0.3325.162)

![image](https://user-images.githubusercontent.com/34940685/55235634-4c161680-522e-11e9-85ee-210643305e57.png)

-I don't know how to chek if my GPU is dedicated or virtual.

**Comment by tecnodcp** [comment]
Happends the same with 73.0.3683.86 version

**Comment by tecnodcp** [comment]
OK perfect. With version  73.0.3683.86  that error doesn't appear anymore
