### ISSUE TITLE
Api not found on BIMserver 1.5.125

### ISSUE THREAD

**Issue by gmdMETIS** [opensourceBIM/BIMsurfer#25]
https://github.com/opensourceBIM/BIMsurfer/blob/5edbd01868d3cf6a22bb42577c10d0bea979fe06/viewer/bimsurfer.js#L4

This row cause a 404 error, using the latest BIMserver 1.5.125. Importing the file from a local path fix the issue.

**Comment by tecnodcp** [comment]
removing the brackets should work

**Comment by gmdMETIS** [comment]
The fact is, in the new BIMServer the api is not present, is not available as plugin and I cannot find some reference on the documentation...

**Comment by tecnodcp** [comment]
I've installed the plugin here
![image](https://user-images.githubusercontent.com/34940685/55235197-43711080-522d-11e9-9661-5c5d4c428cd2.png)

> install from URL or File
I've loaded the bimserverapi-0.0.147.jar and it appears now in the web modules

![image](https://user-images.githubusercontent.com/34940685/55235371-b4b0c380-522d-11e9-88b1-2eaa9f2214a6.png)

**Comment by rubendel** [comment]
There are three scenarios:
- You are using the built version of BIMsurfer, in that case, the BimServerJavaScript API is included and the mentioned import is actually rewritten to a relative location
- You are using the development version of BIMsurfer and serving it from a BIMserver. In this case you indeed need to have the BimServerJavaScript API webmodule installed on your BIMserver. You can do this directly from the source or install a built version of the API (like @tecnodcp showed, except you don't need to upload a file, you can use the maven repository)
- You are serving BIMsurfer 3 from your own webserver, either in a development situation, or online. In that case you need to make sure the mentioned path is updated to wherever you place the BimServerJavaScript API, either in your own buildscript, or manually.

**Comment by gmdMETIS** [comment]
Thanks @tecnodcp , installing and removing the brackets did the trick ;-)

@rubendel I'm actually on the third case, a local modified version of BIMSurfer with the jar BIMServer on the local machine
