### ISSUE TITLE
The model does not display all elements

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMsurfer#27]
Hello,

I use default settings for showing model, but does not display all ifc elements. How do I change the settings to display all the elements?

Thanks

**Comment by rubendel** [comment]
Have you looked in defaultsettings.js?

**Comment by titanDevelopers** [comment]
I don't change anything in defaultsettings.js.

**Comment by rubendel** [comment]
You don't have to, that's why I asked whether you had **looked** at it.

It's a good resource to find available settings, for example: 
```json
settings.excludedTypes = ["IfcSpace", "IfcOpeningElement", "IfcAnnotation"];
```

https://github.com/opensourceBIM/BIMsurfer/blob/master/viewer/defaultsettings.js#L81

**Comment by JanoSlivka** [comment]
That's good, but does not display for example IfcBuildingElementProxy. A specific model have about 4 000 000 triangles and triangleThresholdDefaultLayer is set to 1 000 000 (by default). I increase triangleThresholdDefaultLayer  to 5 000 000, surfer displays all elements, but rendering is slower (some models not display). How to show all elements with more triangles?

**Comment by rubendel** [comment]
That's a good way of making sure more triangles are shown. Another way is to enable the tiling layer (the remaining triangles, so all above the threshold, will be drawn by that layer). The tiling layer is a bit smarter than the default layer in that it uses tiling. Render performance however mainly depends on your GPU.

**Comment by JanoSlivka** [comment]
But by default is tiling layer enabled and does not display elements above the threshold.
