### ISSUE TITLE
No selection on firefox only

### ISSUE THREAD

**Issue by Chris-12** [opensourceBIM/BIMsurfer#36]
Hello,
On Firefox67.0(64bits). On Bimsurfer3.0.0.239 (with server 1.5.147), renderbuffer.js raised a WebGL warning, preventing to select objects by clicking on models with the mouse. This did not occure on Chrome. 
It seems that function (line130) read(pickX, pickY) causes this because of a webgl not clear spec about format/type combinations. For having this solved in both chrome and firefox, I've changed
var pix = new Uint8Array(4); (line133)
to
var pix = new Uint32Array(4);
And 
gl.readPixels(x, y, 1, 1, gl.RGBA_INTEGER, gl.UNSIGNED_BYTE, pix); (line137)
to
gl.readPixels(x, y, 1, 1, gl.RGBA_INTEGER, gl.UNSIGNED_INT, pix);

There is also an other warning, line 146 on readPixels in depth() function for the same reason of format/type combination.
Regards,
Chris

**Comment by aothms** [comment]
Thanks, we do test with Firefox, so probably this is something hardware or driver dependent. Can you turn this into an actual pull request so that we can retain the author information? Thanks in advance.
