### ISSUE TITLE
Problem with comparison in AvlTree

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMsurfer#45]
Hello,

compare function in AvlTree not working good, when use defaultSetting (useUuidAndRid = false). 

By default use in viewer:
this.uniqueIdCompareFunction = (a, b) => {
    return a - b;
};

In AvlTree compare value only with result (-1,0,1) and function _uniqueIdCompareFunction_ not return only -1, 0, 1.

**Comment by rubendel** [comment]
Yes, AvlTree only uses the -1, 0 and 1 values, but all values are passed through https://github.com/opensourceBIM/BIMsurfer/blob/master/viewer/collections/binarysearchtree.js#L46 if I'm not mistaken.

**Comment by JanoSlivka** [comment]
ok, but compareFn is always defined, then condition is always true and use compareFn.

https://github.com/opensourceBIM/BIMsurfer/blob/294e32cb5c853bd77f6c32b6f8550cacdabc7a52/viewer/viewer.js#L115-L130

**Comment by rubendel** [comment]
Ah good catch! Will fix
