### ISSUE TITLE
Section plane along vertical or horizontal axis

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMsurfer#48]
Hello,

it is also possible to section model along a vertical or horizontal axis (not only elements).

Thanks

**Comment by aothms** [comment]
Not from the UI. Programmatically you just need to set the four values of a plane equation. Have a look here https://github.com/opensourceBIM/BIMsurfer/blob/master/viewer/viewer.js#L702

**Comment by JanoSlivka** [comment]
OK, thanks, I'll try it.
