### ISSUE TITLE
Section plane performance

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMsurfer#52]
Hello,

I enable section plane, then cutting the model. Consequently the rotating with the model is slow and model tearing (mostly bigger model -> more triangles). Why? Then disable section plane, everything is ok.

Thanks

**Comment by aothms** [comment]
The section plane itself does not affect performance a lot. But we use the stencil buffer to draw [1] a 'cap' over manifold solid objects (similar to [2]) this requires the scene to be drawn multiple times to fill the stencil buffer. It can be disabled (when navigating) or be made more efficient by only rendering octree tiles intersecting with the section plane.

[1] https://github.com/opensourceBIM/BIMsurfer/blob/master/viewer/viewer.js#L535 
[2] http://glbook.gamedev.net/GLBOOK/glbook.gamedev.net/moglgp/advclip.html

**Comment by JanoSlivka** [comment]
ok, thanks
