### ISSUE TITLE
Measure feature

### ISSUE THREAD

**Issue by mantinha** [opensourceBIM/BIMsurfer#54]
Is there any feature I can use to measure a 3D object in navigation? For example, I give a point "A" and a point "B" and get the distance between those points. Getting the elevation measurement would also be good.

**Comment by rubendel** [comment]
Nope, no such feature in this version

**Comment by mantinha** [comment]
I'm trying to implement the functionality of measuring model points using xeokit and I need the model's demand to be 100% available but I believe that BIMsurfer loads the models as they become visible. For this reason when reading the used protocol it gives error.

![image](https://user-images.githubusercontent.com/25441376/73294515-c748b000-41e4-11ea-9140-d468ea459931.png)

I don't know exactly where the BIMServer binary data format is implemented to implement a protocol that is viable.
I am trying to perform reverse engineering on BIMsurfer to solve this problem.
