### ISSUE TITLE
vertex and shader WebGL2RenderingContext error

### ISSUE THREAD

**Issue by halmsx** [opensourceBIM/BIMsurfer#64]
im trying out bimsurfer bimsurfer3-0.0.270 example files with bimserver 1.5.180,  and got into this errors. using mac catalina with latest chrome and firefox.

<img width="1436" alt="Screenshot 2020-01-06 at 1 06 45 PM" src="https://user-images.githubusercontent.com/7524731/71796737-2a33a500-3086-11ea-8ad7-c85ccedace2c.png">

chrome error: Uncaught (in promise) TypeError: Failed to execute 'attachShader' on 'WebGL2RenderingContext': parameter 2 is not of type 'WebGLShader'.
 
in firefox it says TypeError: Argument 2 of WebGL2RenderingContext.attachShader is not an object

tried with bimserverapi 0.0.167 through 0.0.176.

what should be a working combination?

**Comment by rainerbreuss** [comment]
same Error in 0.0.272-SNAPSHOT:
(tested with Chrome and FireFox)

`vertex shader  programmanager.js:337`

|  method  | file  | line  |
|---|---|---:|
| loadShader | @ programmanager.js | 337 |
| initShaderProgram | @ programmanager.js | 285 |
| (anonymous) | @ programmanager.js | 226 |
| setupProgram | @ programmanager.js | 225 |
| generateShaders | @ programmanager.js | 163 |
| load | @ programmanager.js | 117 |
| (anonymous) | @ viewer.js | 435 |
| init | @ viewer.js | 416 |
| loadRevisionsByRoids | @ bimserverviewer.js | 60 |

**Comment by mantinha** [comment]
If you want to capture the canvas tag you can reach the Webgl2 property

![image](https://user-images.githubusercontent.com/25441376/73386566-cf205700-42ad-11ea-938d-982f15b10464.png)

Here it worked!

**Comment by rubendel** [comment]
This is kind of fixed (please read the commit message for more info), will be in the next release.
