### ISSUE TITLE
BIMsurfer3: Zoom to selected element doesn't work

### ISSUE THREAD

**Issue by rainerbreuss** [opensourceBIM/BIMsurfer#67]
method `viewFit(id)` in File `viewer.js` doesn't work.

It seems that the`aabb` of the selected element has to be transformed with the `globalTransformation` of the viewer before it is passed to `camera.viewFit(aabb)`

**Comment by rainerbreuss** [comment]
works in current version, has been a mistake copying files from a to b ...

**Comment by sadsasuke** [comment]
what is aabb?
