### ISSUE TITLE
Rotate model to specific face

### ISSUE THREAD

**Issue by TitouanGisle** [opensourceBIM/BIMsurfer#69]
Hello !

I have been looking into the code for a few hours now trying to find a way to display the model with a specific side facing the camera. (top side, left side, and so on)

All my attempts have been unsuccessful so far, so I turn to you, hoping that you might have a hint.

I have tried with bimserverViewer.viewer.camera.viewFit(), and applied all kind of transformation to the bounding box it takes as a parameter, but it doesn't do the trick.

Do I have to manually calculate the camera's position according to the model's face ? If so, do you know how to get the model's faces ?

Thanks for your consideration !

**Comment by saadaiforsite** [comment]
hi @TitouanGisle , how were you able to use bimserverViewer.viewer.camera.viewFit() i have been trying but it says its not a function. can you share some relevant code. thanks

**Comment by TitouanGisle** [comment]
Hi !
We've stopped using BIMsurfer around 4 years ago, so I'm afraid I can't help you.
Best of luck.
