### ISSUE TITLE
Large model view is trimmed 

### ISSUE THREAD

**Issue by bdamay** [opensourceBIM/BIMsurfer#82]
Hi, 
While loading geographically large models  on bimsurfer, i'm getting a trimmed result in the view and i can't figure out to enlarge the view. 
I tried increasing fov near and far values in perspective.js but with not much success. The view remains trimmed in a limited frustum that doesn't allow me to see all the model. 

On another hand i can see the full model mesh is actually loaded as i can see it in the view while it is selected: 
![issue_github_fov](https://user-images.githubusercontent.com/16347726/105629615-52827300-5e44-11eb-8972-7020d4522f59.png)

Help on how to solve this would be much appreciated.

Best regards
Benoit

**Comment by aothms** [comment]
Yep, a commit made it into master that shouldn't have been there probably for general purpose use. You might want to not upgrade to e64a6ef7d5090e9998c2387e834a5a1d8a1e52c1 (or revert the changes in viewer/shaders/fragment.glsl.js) until we have made this properly conditional.

**Comment by bdamay** [comment]
Thanks for answering so quickly.
This works fine for my needs . 

For the record, I checked out the file to a067652.
