### ISSUE TITLE
Project is missing a meaningful description

### ISSUE THREAD

**Issue by DuncanLithgow** [opensourceBIM/BIMsurfer#90]
This page: https://github.com/opensourceBIM/BIMsurfer

The project is missing a meaningful description. I wanted to add a description to the osarch.org list of projects using IfcOpenShell https://wiki.osarch.org/index.php?title=IfcOpenShell but can find no meaningful description.

**Comment by aothms** [comment]
You're right duncan. I've pasted a bit from the bimsurfer2 repo.
