### ISSUE TITLE
How do I get building component information, such as names

### ISSUE THREAD

**Issue by znnspace** [opensourceBIM/BIMsurfer#95]
How do I get building component information, such as names

**Comment by aothms** [comment]
If you use the open source bimserver, there are still some snippets in this repo https://github.com/AECgeeks/BIMsurfer2/blob/master/bimsurfer/src/MetaDataRenderer.js to query the model for element attributes and property sets.

**Comment by znnspace** [comment]
I am using BIMSurfer v3 version
